import {
  IconCoins,
  IconComponent,
  IconCurrencyAfghani,
  IconCurrencyBahraini,
  IconCurrencyBaht,
  IconCurrencyForint,
  IconCurrencyDinar,
  IconCurrencyDirham,
  IconCurrencyDollar,
  IconCurrencyDollarAustralian,
  IconCurrencyDollarBrunei,
  IconCurrencyDollarCanadian,
  IconCurrencyDollarGuyanese,
  IconCurrencyDollarSingapore,
  IconCurrencyDong,
  IconCurrencyDram,
  IconCurrencyEuro,
  IconCurrencyFlorin,
  IconCurrencyFrank,
  IconCurrencyGuarani,
  IconCurrencyHryvnia,
  IconCurrencyIranianRial,
  IconCurrencyKip,
  IconCurrencyKroneCzech,
  IconCurrencyKroneDanish,
  IconCurrencyKroneSwedish,
  IconCurrencyLari,
  IconCurrencyLeu,
  IconCurrencyLira,
  IconCurrencyLyd,
  IconCurrencyManat,
  IconCurrencyNaira,
  IconCurrencyPaanga,
  IconCurrencyPeso,
  IconCurrencyPound,
  IconCurrencyQuetzal,
  IconCurrencyReal,
  IconCurrencyRenminbi,
  IconCurrencyRiyal,
  IconCurrencyRubel,
  IconCurrencyRufiyaa,
  IconCurrencyRupee,
  IconCurrencyRupeeNepalese,
  IconCurrencyTaka,
  IconCurrencyTenge,
  IconCurrencyTugrik,
  IconCurrencySom,
  IconCurrencyShekel,
  IconCurrencyWon,
  IconCurrencyYen,
  IconCurrencyYuan,
  IconCurrencyZloty,
} from 'twenty-ui';

import { CurrencyCode } from '@/object-record/record-field/types/CurrencyCode';

export const SETTINGS_FIELD_CURRENCY_CODES: Record<
  CurrencyCode,
  { label: string; Icon: IconComponent }
> = {
  BRL: { label: 'Real brasileiro', Icon: IconCurrencyReal },
  USD: { label: 'Dólar americano', Icon: IconCurrencyDollar },
  EUR: { label: 'Euro', Icon: IconCurrencyEuro },
  AED: { label: 'Dirham dos Emirados Árabes', Icon: IconCurrencyDirham },
  AFN: { label: 'Afeganistani afghani', Icon: IconCurrencyAfghani },
  ALL: { label: 'Lek albanês', Icon: IconCurrencyLeu },
  AMD: { label: 'Dram armênio', Icon: IconCurrencyDram },
  ANG: { label: 'Guilder das Antilhas Holandesas', Icon: IconCurrencyFlorin },
  AOA: { label: 'Kwanza angolano', Icon: IconCoins },
  ARS: { label: 'Peso argentino', Icon: IconCoins },
  AUD: { label: 'Dólar australiano', Icon: IconCurrencyDollarAustralian },
  AWG: { label: 'Florim arubano', Icon: IconCurrencyFlorin },
  AZN: { label: 'Manat azerbaijano', Icon: IconCurrencyManat },
  BAM: { label: 'Marco bósnio', Icon: IconCoins },
  BBD: { label: 'Dólar de Barbados', Icon: IconCurrencyDollar },
  BDT: { label: 'Taka de Bangladesh', Icon: IconCurrencyTaka },
  BGN: { label: 'Lev búlgaro', Icon: IconCoins },
  BHD: { label: 'Dinar do Bahrein', Icon: IconCurrencyBahraini },
  BIF: { label: 'Franco burundense', Icon: IconCoins },
  BMD: { label: 'Dólar bermudense', Icon: IconCurrencyDollar },
  BND: { label: 'Dólar de Brunei', Icon: IconCurrencyDollarBrunei },
  BOB: { label: 'Boliviano', Icon: IconCoins },
  BSD: { label: 'Dólar das Bahamas', Icon: IconCurrencyDollar },
  BTN: { label: 'Ngultrum butanês', Icon: IconCurrencyDollar },
  BWP: { label: 'Pula de Botswana', Icon: IconCoins },
  BYN: { label: 'Rublo bielorrusso', Icon: IconCoins },
  BZD: { label: 'Dólar de Belize', Icon: IconCurrencyDollar },
  CAD: { label: 'Dólar canadense', Icon: IconCurrencyDollarCanadian },
  CDF: { label: 'Franco congolês', Icon: IconCoins },
  CHF: { label: 'Franco suíço', Icon: IconCurrencyFrank },
  CLP: { label: 'Peso chileno', Icon: IconCoins },
  CNY: { label: 'Yuan chinês', Icon: IconCurrencyYuan },
  COP: { label: 'Peso colombiano', Icon: IconCoins },
  CRC: { label: 'Colón costarriquenho', Icon: IconCoins },
  CUP: { label: 'Peso cubano', Icon: IconCoins },
  CVE: { label: 'Escudo cabo-verdiano', Icon: IconCoins },
  CZK: { label: 'Coroa checa', Icon: IconCurrencyKroneCzech },
  DJF: { label: 'Franco djibutiano', Icon: IconCoins },
  DKK: { label: 'Coroa dinamarquesa', Icon: IconCurrencyKroneDanish },
  DOP: { label: 'Peso dominicano', Icon: IconCoins },
  DZD: { label: 'Dinar argelino', Icon: IconCoins },
  EGP: { label: 'Libra egípcia', Icon: IconCoins },
  ERN: { label: 'Nakfa eritreu', Icon: IconCoins },
  ETB: { label: 'Birr etíope', Icon: IconCoins },
  FJD: { label: 'Dólar de Fiji', Icon: IconCurrencyDollar },
  FKP: { label: 'Libra das Ilhas Falkland', Icon: IconCoins },
  GBP: { label: 'Libra esterlina', Icon: IconCurrencyPound },
  GEL: { label: 'Lari georgiano', Icon: IconCurrencyLari },
  GHS: { label: 'Cedi ganês', Icon: IconCoins },
  GIP: { label: 'Libra de Gibraltar', Icon: IconCoins },
  GMD: { label: 'Dalasi gambiano', Icon: IconCoins },
  GNF: { label: 'Franco guineense', Icon: IconCoins },
  GTQ: { label: 'Quetzal guatemalteco', Icon: IconCurrencyQuetzal },
  GYD: { label: 'Dólar guianense', Icon: IconCurrencyDollarGuyanese },
  HKD: { label: 'Dólar de Hong Kong', Icon: IconCurrencyRenminbi },
  HNL: { label: 'Lempira hondurenha', Icon: IconCurrencyLeu },
  HTG: { label: 'Gourde haitiano', Icon: IconCoins },
  HUF: { label: 'Forint húngaro', Icon: IconCurrencyForint },
  IDR: { label: 'Rupia indonésia', Icon: IconCoins },
  ILS: { label: 'Shekel israelense', Icon: IconCurrencyShekel },
  INR: { label: 'Rupia indiana', Icon: IconCurrencyRupee },
  IQD: { label: 'Dinar iraquiano', Icon: IconCoins },
  IRR: { label: 'Rial iraniano', Icon: IconCurrencyIranianRial },
  ISK: { label: 'Coroa islandesa', Icon: IconCoins },
  JMD: { label: 'Dólar jamaicano', Icon: IconCurrencyDollar },
  JOD: { label: 'Dinar jordaniano', Icon: IconCoins },
  JPY: { label: 'Iene japonês', Icon: IconCurrencyYen },
  KES: { label: 'Xelim queniano', Icon: IconCoins },
  KGS: { label: 'Som quirguiz', Icon: IconCurrencySom },
  KHR: { label: 'Riel cambojano', Icon: IconCoins },
  KMF: { label: 'Franco comorense', Icon: IconCoins },
  KPW: { label: 'Won norte-coreano', Icon: IconCurrencyWon },
  KRW: { label: 'Won sul-coreano', Icon: IconCurrencyWon },
  KWD: { label: 'Dinar kuwaitiano', Icon: IconCurrencyDinar },
  KYD: { label: 'Dólar das Ilhas Cayman', Icon: IconCurrencyDollar },
  KZT: { label: 'Tenge cazaque', Icon: IconCurrencyTenge },
  LAK: { label: 'Kip lao', Icon: IconCurrencyKip },
  LBP: { label: 'Libra libanesa', Icon: IconCoins },
  LKR: { label: 'Rupia do Sri Lanka', Icon: IconCoins },
  LRD: { label: 'Dólar liberiano', Icon: IconCurrencyDollar },
  LSL: { label: 'Loti do Lesoto', Icon: IconCurrencyLeu },
  LYD: { label: 'Dinar líbio', Icon: IconCurrencyLyd },
  MAD: { label: 'Dirham marroquino', Icon: IconCurrencyDirham },
  MDL: { label: 'Leu moldavo', Icon: IconCurrencyLeu },
  MGA: { label: 'Ariary malgaxe', Icon: IconCoins },
  MKD: { label: 'Dinar macedônio', Icon: IconCoins },
  MMK: { label: 'Kyat birmanês', Icon: IconCoins },
  MNT: { label: 'Tögrög mongol', Icon: IconCurrencyTugrik },
  MOP: { label: 'Pataca de Macau', Icon: IconCurrencyRenminbi },
  MRU: { label: 'Ouguiya mauritano', Icon: IconCoins },
  MUR: { label: 'Rupia mauriciana', Icon: IconCoins },
  MVR: { label: 'Rufiyaa das Maldivas', Icon: IconCurrencyRufiyaa },
  MWK: { label: 'Kwacha do Malauí', Icon: IconCoins },
  MXN: { label: 'Peso mexicano', Icon: IconCoins },
  MYR: { label: 'Ringgit malaio', Icon: IconCoins },
  MZN: { label: 'Metical moçambicano', Icon: IconCoins },
  NAD: { label: 'Dólar namibiano', Icon: IconCurrencyDollar },
  NGN: { label: 'Naira nigeriana', Icon: IconCurrencyNaira },
  NIO: { label: 'Córdoba nicaraguense', Icon: IconCoins },
  NOK: { label: 'Coroa norueguesa', Icon: IconCurrencyKroneSwedish },
  NPR: { label: 'Rupia nepalense', Icon: IconCurrencyRupeeNepalese },
  NZD: { label: 'Dólar neozelandês', Icon: IconCurrencyDollar },
  OMR: { label: 'Rial omani', Icon: IconCoins },
  PAB: { label: 'Balboa panamenho', Icon: IconCoins },
  PEN: { label: 'Sol peruano', Icon: IconCoins },
  PGK: { label: 'Kina da Papua Nova Guiné', Icon: IconCoins },
  PHP: { label: 'Peso filipino', Icon: IconCurrencyPeso },
  PKR: { label: 'Rupia paquistanesa', Icon: IconCoins },
  PLN: { label: 'Zloty polonês', Icon: IconCurrencyZloty },
  PYG: { label: 'Guaraní paraguaio', Icon: IconCurrencyGuarani },
  QAR: { label: 'Riyal catarense', Icon: IconCurrencyRiyal },
  RON: { label: 'Leu romeno', Icon: IconCurrencyLeu },
  RSD: { label: 'Dinar sérvio', Icon: IconCoins },
  RUB: { label: 'Rublo russo', Icon: IconCurrencyRubel },
  RWF: { label: 'Franco ruandense', Icon: IconCoins },
  SAR: { label: 'Riyal saudita', Icon: IconCoins },
  SBD: { label: 'Dólar das Ilhas Salomão', Icon: IconCurrencyDollar },
  SCR: { label: 'Rupia das Seychelles', Icon: IconCoins },
  SDG: { label: 'Libra sudanesa', Icon: IconCoins },
  SEK: { label: 'Coroa sueca', Icon: IconCurrencyKroneSwedish },
  SGD: { label: 'Dólar de Singapura', Icon: IconCurrencyDollarSingapore },
  SHP: { label: 'Libra de Santa Helena', Icon: IconCoins },
  SLE: { label: 'Leão de Serra Leoa', Icon: IconCoins },
  SOS: { label: 'Xelim somali', Icon: IconCoins },
  SRD: { label: 'Dólar surinamense', Icon: IconCurrencyDollar },
  SSP: { label: 'Libra do Sudão do Sul', Icon: IconCoins },
  STN: { label: 'Dobra de São Tomé e Príncipe', Icon: IconCoins },
  SVC: { label: 'Colón salvadorenho', Icon: IconCoins },
  SYP: { label: 'Libra síria', Icon: IconCoins },
  SZL: { label: 'Lilangeni da Suazilândia', Icon: IconCurrencyLeu },
  THB: { label: 'Baht tailandês', Icon: IconCurrencyBaht },
  TJS: { label: 'Somoni do Tajiquistão', Icon: IconCoins },
  TMT: { label: 'Manat do Turcomenistão', Icon: IconCurrencyManat },
  TND: { label: 'Dinar tunisiano', Icon: IconCoins },
  TOP: { label: 'Paʻanga de Tonga', Icon: IconCurrencyPaanga },
  TRY: { label: 'Lira turca', Icon: IconCurrencyLira },
  TTD: { label: 'Dólar de Trinidad e Tobago', Icon: IconCurrencyDollar },
  TWD: { label: 'Dólar taiwanês', Icon: IconCurrencyRenminbi },
  TZS: { label: 'Xelim da Tanzânia', Icon: IconCoins },
  UAH: { label: 'Hryvnia ucraniana', Icon: IconCurrencyHryvnia },
  UGX: { label: 'Xelim ugandense', Icon: IconCoins },
  UYU: { label: 'Peso uruguaio', Icon: IconCoins },
  UZS: { label: 'Sum uzbeque', Icon: IconCoins },
  VES: { label: 'Bolívar venezuelano', Icon: IconCoins },
  VND: { label: 'Dong vietnamita', Icon: IconCurrencyDong },
  VUV: { label: 'Vatu de Vanuatu', Icon: IconCoins },
  WST: { label: 'Tala samoano', Icon: IconCoins },
  XCD: { label: 'Dólar do Caribe Oriental', Icon: IconCurrencyDollar },
  YER: { label: 'Rial iemenita', Icon: IconCoins },
  ZAR: { label: 'Rand sul-africano', Icon: IconCoins },
  ZMW: { label: 'Kwacha zambiano', Icon: IconCoins },
  ZWG: { label: 'Ouro do Zimbábue', Icon: IconCoins },
};
